version: "3.9"

services:
  messagebus:
    image: rabbitmq:latest

  loggingservice:
    container_name: loggingservice
    build:
      context: ./loggingservice
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - MESSAGE_QUEUE=amqp://messagebus
      - MONGO_URL=mongodb://loggingdb:loggingdbpass@loggingdb:27017/
    depends_on:
      - "messagebus"
      - "loggingdb"
  
  authservice:
    container_name: authservice
    build:
      context: ./authservice
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "3001:3001"
    expose:
      - "3001"
    environment:
      - MONGO_URL=mongodb://authdb:authdbpass@authdb:27018/
    depends_on:
      - "authdb"

  dataservice:
    container_name: dataservice
    build:
      context: ./dataservice/dataservice
      dockerfile: Dockerfile
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      - MSSQL_URL_USER_DATA=mongodb://userdatadb:userdatadbpass@userdatadb:27017/
      - MSSQL_URL_GENERAL_DATA=mongodb://generaldatadb:generaldatadbpass@generaldatadb:27017/
    depends_on:
      - "userdatadb"
      - "generaldatadb"
      - "loggingservice"

  web:
    container_name: web
    build:
      context: ./web/web
      dockerfile: Dockerfile
    ports:
      - "81:80"
    expose:
      - "81"
    depends_on:
      - "dataservice"

  loggingdb:
    container_name: loggingdb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: loggingdb
      MONGO_INITDB_ROOT_PASSWORD: loggingdbpass
    ports:
      - 27017:27017
    expose:
      - "27017"
    restart: always
    volumes:
      - loggingdb_volume:/data/db
  
  authdb:
    container_name: authdb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: authdb
      MONGO_INITDB_ROOT_PASSWORD: authdbpass
    ports:
      - 27018:27018
    expose:
      - "27018"
    restart: always
    volumes:
      - authdb_volume:/data/db

  userdatadb:
    container_name: userdatadb
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: mssql
    environment:
      MSSQL_SA_PASSWORD: UserDataDBPass123545!@
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    expose:
      - "1433"
    restart: always
    volumes:
      - userdatadb_volume:/var/opt/mssql

  generaldatadb:
    container_name: generaldatadb
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: mssql
    environment:
      MSSQL_SA_PASSWORD: GeneralDataDBPass12345!@
      ACCEPT_EULA: Y
    ports:
      - 1434:1433
    expose:
      - "1434"
    restart: always
    volumes:
      - generaldatadb_volume:/var/opt/mssql

volumes:
  loggingdb_volume:
  authdb_volume:
  userdatadb_volume:
  generaldatadb_volume:
