version: "3.9"

services:
  messagebus:
    image: rabbitmq:latest

  loggingservice:
    container_name: loggingservice
    build:
      context: ./loggingservice
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - MESSAGE_QUEUE=amqp://messagebus
      - MONGO_URL=mongodb://loggingdb:loggingdbpass@loggingdb:27017/
    depends_on:
      - "messagebus"
      - "loggingdb"

  dataservice:
    container_name: dataservice
    build:
      context: ./dataservice
      dockerfile: Dockerfile
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      - MSSQL_URL_USER_DATA=mongodb://userdatadb:userdatadbpass@userdatadb:27017/
      - MSSQL_URL_GENERAL_DATA=mongodb://generaldatadb:generaldatadbpass@generaldatadb:27017/
    depends_on:
      - "userdatadb"
      - "generaldatadb"
      - "loggingservice"

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "81:80"
    expose:
      - "81"
    depends_on:
      - "dataservice"

  loggingdb:
    container_name: loggingdb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: loggingdb
      MONGO_INITDB_ROOT_PASSWORD: loggingdbpass
    ports:
      - 27017:27017
    expose:
      - "27017"
    restart: always

  userdatadb:
    container_name: userdatadb
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: userdatadb
      MONGO_INITDB_ROOT_PASSWORD: userdatadbpass
    ports:
      - 1433:1433
    expose:
      - "1433"
    restart: always

  generaldatadb:
    container_name: generaldatadb
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: generaldatadb
      MONGO_INITDB_ROOT_PASSWORD: generaldatadbpass
    ports:
      - 1434:1433
    expose:
      - "1434"
    restart: always
