name: Build and release android app

defaults:
    run:
      working-directory: './mobileapp'

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build-and-deploy:

    name: Build/Sign APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Tag
      id: var
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Build APK
      id: build
      run: bash ./gradlew assembleRelease

    - name: Sign APK
      id: sign_apk
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: ./mobileapp/app/build/outputs/apk/release
        signingKeyBase64: MIIJ0wIBAzCCCYwGCSqGSIb3DQEHAaCCCX0Eggl5MIIJdTCCBYEGCSqGSIb3DQEHAaCCBXIEggVuMIIFajCCBWYGCyqGSIb3DQEMCgECoIIE+zCCBPcwKQYKKoZIhvcNAQwBAzAbBBQhdYNY8iuP/NYWHKslBPWAmjrt3wIDAMNQBIIEyE8zZVDpAfTFFLt9/synVak4KH6e9aM1iR/y/3+4sS2tUJhoVZSqr6lBzzNkhcPnmSDWN4YKTIUzAr3Q8oAsn96lRYEAWQ4nbiorHhkopncMtFSAoptGR3TCA8ltagdU7e+p0wqEwco2/B2vHVg1W5Oe9p2fdnGNFgNh+jy/1xYLkUxFOpEkQKCTLffw/s+j2Z4EtsWATWf4GXZgYzevAmDpelMXnjiPm8z1HeLeAdpmB4hTmYWFem3tu9Qb59XaEB8IPFHN8yvV45EqIGLNVbIFTYlUYwKF/cQAnTLVCq5Xaysqjv0D76ICn3j02d0R+oyGX6XFvLSA9teGtBDaYOGF/7M1GIt3K/KPPZDeImYQg2PIjyl6CZMhbQKYSnW38sUXEP+6Ii2Sm+NG5yqFcfolgW8qixxiRd2SY7PumGEmKq6TB9XJwc2B//SQ2vd57YV9969I78uJfrNWylRpQpbRfY6QHlBXoGCbd8KCZlfvX9Py0m1FLDkV5fJz0dBCzHU5INPpW3BWgKIhyRABpuhkkqzV8CDKskKhdnpJ9A1rbLbg5jqRvyDVIiTonAD6IiEwVDqnnqjsungvBFslBP0U8Fhl691U6IZ1LqkzJFMi9JaZVlz0sluTaBiZut84HY6rCFbrujloxYQPKNdqmF4ciTQu6cHLtPx3t5EbHlLxigAZFnfw3uMiBT6S9Z3NoB8lPPnDtmSbxEfqZvp/SotpcP3MgAGSiAYnpJLmk1gw/Yj+A6ViJZr755hacnQgXy8CoeIuxxs0c+Sus37KGcIoUELl3PNzP9c7ikQQ/bHcaJ2RTwn870L3RdkK2px6OD29EqOiubI9gdWXd3XFrkTShzlB7TuWHmm7FMA999tpa/oC1rGvYNnQoR58cKKbSmeJREHPWnKdK5RozOPa+LPgL0TwkOokBsLzAEqu8y9YycxXw1iyNGHUQGRNrZVMgx6QjYYcRhWL7h8Xwjcpic2PJJuUUeDfBVsZB8QLiwOb5qmohbOw0NDFRrW/mCqhJFc7TL3gbvBC8MnHh4aIJNBADq+2K01ordu7u2KneU9wVR4aHunhHGlGUk14b5LKKdret7aNB41LF1ifzDzkfqGK7U6Gg7bDdwpyHRXnvzEc1PZpDWkhUEuUz/jXbLY1puYrTIv7T1NTiQRUPSNq1++ojqLq8AyKjg+QBzhIpl2EPlpBN31APzO2SON4hy5aTgPx45dXo8zytN0DyPq1KFCntXEmcHvEeaLIZfiyWRjdHVi/Lx2tQUs+16QuykLyL6/t2YNADrk0vIzIci2AUKbzTKuvriKb+couudgK8hfw2SDXsbhfrwc0PCMWa+WRKAn/Yq+535nu7T4PEZx8C4fvfznUNKz4H9gMWoo0F0eFLLfsrXV5gSN6L0ZjBYXja229ieM9NCuKtY+CARGUxVmFfl3TI39pnNwmFMAPJKdsy4H5s06q3yWcV5A/C9RMEoqXU7PDpEms5U0LvXEAwxgN5wfqYCHvK5r8CTs/k4B0YE4yDwRqf68eDa7YTuVpiO45hAU3RaiUv3hzZQdekgZz1XnUp/1pXkNI2shBOxQmDElvai8yMLlT214gEyr9dA0Zu9ycj0xO2zG5Xw01+RaBH/7vYz0vKDFYMDMGCSqGSIb3DQEJFDEmHiQAaQBzAHYAaQByAHQAdQBhAGwAYQBzAHMAaQBzAHQAZQBuAHQwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTY1MDE1MDU4MzU2ODCCA+wGCSqGSIb3DQEHBqCCA90wggPZAgEAMIID0gYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQUCTRxJlEAAvkXKpCx0nQeFvPiUWICAwDDUICCA5gcwpFHPAVmUuoKUHcJjRUlAxmmQWt37ZZCoXc8cH6EzaLLQRm5HXn/Ndd8ubcjhu9IarJQLqYiMnSdFpOKRX+5N8OA9shK5i8McHz+srqwKqCPx4TgeeGH48lhKJrEWWA26xOL3/tSFRtw3vI6Aa7r/4XmJPs8yD4sfe9AfDYVKAdxJnwi+wNCmW68bP2d6l4BVRDhBebp8IRudZI3PlpWAOijUlD4rTQyE827RD7Ony/GDKZ9ZOs0owEKcNAjcBpisuZEmWEUvicrvnbeY6eN2Job95thKZtIlVB3uxGGrGLMgy+JcIynrwvUDmH2hQeDajmwQlPHv0MlBIPyVDMDPEYw1Axq/tGlXWVZMmFuPJKUTBKlszdxU/LRBMWmXWNrowsb4lbwYNpEra93R/vVCBM3QLRSh4vrlhuJtDV5V/BOi1UyFSBJTN/3uZ1dlTAtSn/Fu1O4ZdL/T6273dqwSu5jkZv7icYVQ/nyXiRDZ5o+P79cTw3ho7bOgFGOA1kTXusDVp3/u7skb+eqOaK/mWKsKqWc4h9U1loZ8oTE0juTWK5jMgcAsfJ7Ab4/aMHvZ6vYHnDnko1x4pVQnwGFcZR+IArW33NX06TSreZvzph5w5D4MYZqovjGOKIZOVpdeP/w/73wc8chCaBxhpTUcYAhXieH2ZyQuWpstmIct1DgOKpUEwv2uiGEqkeTiUonh80YzgmHEbRWwsqTiWe17B8xtmT3mm1ZIT2fHPduZbWZjqjggpmgF2/TIC64Wk2cU7iRlHDNChDmzMBfB2JiFCF0mHMpmIs/15QsJaGEMY/FQg6Vo34Xr2mSWCeU+fkXRJoWv1c5DUKJ8+G8i09HNu4/kM8ja9uJB/1k/qpa0QKnYQFgDz511eURVbCJS7DDcyKQy0ISgNQngQ7d/8cY57e7+h1gT0kwT+krQ6J2kgnwLb5HxBwhsNh/m35gY0FUjB7vSzkh4E38J49nfddqQksWi15Sv4aXeN4TpOxkmfMvDflOILbXpjzh7YAwMvPeZWAxHQZQDWiJ+YZm0GBPVBuN8o0mpQpSyQpGtUjGa0o9V31o7DmsTfUjPLNw+ZdQwo5S29gU2NhQRxdNJY9bn0W83HAXAc/A74LCX7NhU1ZxY5iFjM9ABYUipzkz6sMVjWEKCR6SoOVWw5Zf+LfzVPWM34js5pYm3QYCNy6RaLWRG+kUXEehT/XiSps2z+wb/U80Z+pC5zA+MCEwCQYFKw4DAhoFAAQU/KkiPXwsO9WYMhQZXnbhV3AtWBAEFFQFQkcofilPYChD/4qemSJc116PAgMBhqA=
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: InfoSupportVirtualAssistant
        keyPassword: ${{ secrets.KEYPASSWORD }}

    - name: Make artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release-signed
        path: ${{steps.sign_apk.outputs.signedReleaseFile}}

    - name: Build AAB
      run: bash ./gradlew bundleRelease

    - name: Sign AAB
      id: sign_aab
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: ./mobileapp/app/build/outputs/bundle/release
        signingKeyBase64: MIIJ0wIBAzCCCYwGCSqGSIb3DQEHAaCCCX0Eggl5MIIJdTCCBYEGCSqGSIb3DQEHAaCCBXIEggVuMIIFajCCBWYGCyqGSIb3DQEMCgECoIIE+zCCBPcwKQYKKoZIhvcNAQwBAzAbBBQhdYNY8iuP/NYWHKslBPWAmjrt3wIDAMNQBIIEyE8zZVDpAfTFFLt9/synVak4KH6e9aM1iR/y/3+4sS2tUJhoVZSqr6lBzzNkhcPnmSDWN4YKTIUzAr3Q8oAsn96lRYEAWQ4nbiorHhkopncMtFSAoptGR3TCA8ltagdU7e+p0wqEwco2/B2vHVg1W5Oe9p2fdnGNFgNh+jy/1xYLkUxFOpEkQKCTLffw/s+j2Z4EtsWATWf4GXZgYzevAmDpelMXnjiPm8z1HeLeAdpmB4hTmYWFem3tu9Qb59XaEB8IPFHN8yvV45EqIGLNVbIFTYlUYwKF/cQAnTLVCq5Xaysqjv0D76ICn3j02d0R+oyGX6XFvLSA9teGtBDaYOGF/7M1GIt3K/KPPZDeImYQg2PIjyl6CZMhbQKYSnW38sUXEP+6Ii2Sm+NG5yqFcfolgW8qixxiRd2SY7PumGEmKq6TB9XJwc2B//SQ2vd57YV9969I78uJfrNWylRpQpbRfY6QHlBXoGCbd8KCZlfvX9Py0m1FLDkV5fJz0dBCzHU5INPpW3BWgKIhyRABpuhkkqzV8CDKskKhdnpJ9A1rbLbg5jqRvyDVIiTonAD6IiEwVDqnnqjsungvBFslBP0U8Fhl691U6IZ1LqkzJFMi9JaZVlz0sluTaBiZut84HY6rCFbrujloxYQPKNdqmF4ciTQu6cHLtPx3t5EbHlLxigAZFnfw3uMiBT6S9Z3NoB8lPPnDtmSbxEfqZvp/SotpcP3MgAGSiAYnpJLmk1gw/Yj+A6ViJZr755hacnQgXy8CoeIuxxs0c+Sus37KGcIoUELl3PNzP9c7ikQQ/bHcaJ2RTwn870L3RdkK2px6OD29EqOiubI9gdWXd3XFrkTShzlB7TuWHmm7FMA999tpa/oC1rGvYNnQoR58cKKbSmeJREHPWnKdK5RozOPa+LPgL0TwkOokBsLzAEqu8y9YycxXw1iyNGHUQGRNrZVMgx6QjYYcRhWL7h8Xwjcpic2PJJuUUeDfBVsZB8QLiwOb5qmohbOw0NDFRrW/mCqhJFc7TL3gbvBC8MnHh4aIJNBADq+2K01ordu7u2KneU9wVR4aHunhHGlGUk14b5LKKdret7aNB41LF1ifzDzkfqGK7U6Gg7bDdwpyHRXnvzEc1PZpDWkhUEuUz/jXbLY1puYrTIv7T1NTiQRUPSNq1++ojqLq8AyKjg+QBzhIpl2EPlpBN31APzO2SON4hy5aTgPx45dXo8zytN0DyPq1KFCntXEmcHvEeaLIZfiyWRjdHVi/Lx2tQUs+16QuykLyL6/t2YNADrk0vIzIci2AUKbzTKuvriKb+couudgK8hfw2SDXsbhfrwc0PCMWa+WRKAn/Yq+535nu7T4PEZx8C4fvfznUNKz4H9gMWoo0F0eFLLfsrXV5gSN6L0ZjBYXja229ieM9NCuKtY+CARGUxVmFfl3TI39pnNwmFMAPJKdsy4H5s06q3yWcV5A/C9RMEoqXU7PDpEms5U0LvXEAwxgN5wfqYCHvK5r8CTs/k4B0YE4yDwRqf68eDa7YTuVpiO45hAU3RaiUv3hzZQdekgZz1XnUp/1pXkNI2shBOxQmDElvai8yMLlT214gEyr9dA0Zu9ycj0xO2zG5Xw01+RaBH/7vYz0vKDFYMDMGCSqGSIb3DQEJFDEmHiQAaQBzAHYAaQByAHQAdQBhAGwAYQBzAHMAaQBzAHQAZQBuAHQwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTY1MDE1MDU4MzU2ODCCA+wGCSqGSIb3DQEHBqCCA90wggPZAgEAMIID0gYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQUCTRxJlEAAvkXKpCx0nQeFvPiUWICAwDDUICCA5gcwpFHPAVmUuoKUHcJjRUlAxmmQWt37ZZCoXc8cH6EzaLLQRm5HXn/Ndd8ubcjhu9IarJQLqYiMnSdFpOKRX+5N8OA9shK5i8McHz+srqwKqCPx4TgeeGH48lhKJrEWWA26xOL3/tSFRtw3vI6Aa7r/4XmJPs8yD4sfe9AfDYVKAdxJnwi+wNCmW68bP2d6l4BVRDhBebp8IRudZI3PlpWAOijUlD4rTQyE827RD7Ony/GDKZ9ZOs0owEKcNAjcBpisuZEmWEUvicrvnbeY6eN2Job95thKZtIlVB3uxGGrGLMgy+JcIynrwvUDmH2hQeDajmwQlPHv0MlBIPyVDMDPEYw1Axq/tGlXWVZMmFuPJKUTBKlszdxU/LRBMWmXWNrowsb4lbwYNpEra93R/vVCBM3QLRSh4vrlhuJtDV5V/BOi1UyFSBJTN/3uZ1dlTAtSn/Fu1O4ZdL/T6273dqwSu5jkZv7icYVQ/nyXiRDZ5o+P79cTw3ho7bOgFGOA1kTXusDVp3/u7skb+eqOaK/mWKsKqWc4h9U1loZ8oTE0juTWK5jMgcAsfJ7Ab4/aMHvZ6vYHnDnko1x4pVQnwGFcZR+IArW33NX06TSreZvzph5w5D4MYZqovjGOKIZOVpdeP/w/73wc8chCaBxhpTUcYAhXieH2ZyQuWpstmIct1DgOKpUEwv2uiGEqkeTiUonh80YzgmHEbRWwsqTiWe17B8xtmT3mm1ZIT2fHPduZbWZjqjggpmgF2/TIC64Wk2cU7iRlHDNChDmzMBfB2JiFCF0mHMpmIs/15QsJaGEMY/FQg6Vo34Xr2mSWCeU+fkXRJoWv1c5DUKJ8+G8i09HNu4/kM8ja9uJB/1k/qpa0QKnYQFgDz511eURVbCJS7DDcyKQy0ISgNQngQ7d/8cY57e7+h1gT0kwT+krQ6J2kgnwLb5HxBwhsNh/m35gY0FUjB7vSzkh4E38J49nfddqQksWi15Sv4aXeN4TpOxkmfMvDflOILbXpjzh7YAwMvPeZWAxHQZQDWiJ+YZm0GBPVBuN8o0mpQpSyQpGtUjGa0o9V31o7DmsTfUjPLNw+ZdQwo5S29gU2NhQRxdNJY9bn0W83HAXAc/A74LCX7NhU1ZxY5iFjM9ABYUipzkz6sMVjWEKCR6SoOVWw5Zf+LfzVPWM34js5pYm3QYCNy6RaLWRG+kUXEehT/XiSps2z+wb/U80Z+pC5zA+MCEwCQYFKw4DAhoFAAQU/KkiPXwsO9WYMhQZXnbhV3AtWBAEFFQFQkcofilPYChD/4qemSJc116PAgMBhqA=
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: InfoSupportVirtualAssistant
        keyPassword: ${{ secrets.KEYPASSWORD }}

    - name: Make artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release-signed
        path: ${{steps.sign_aab.outputs.signedReleaseFile}}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload APK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{steps.sign_apk.outputs.signedReleaseFile}}
        asset_name: app-release-signed-${{ steps.var.outputs.tag }}.apk
        asset_content_type: application/zip

    - name: Upload AAB
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{steps.sign_aab.outputs.signedReleaseFile}}
        asset_name: app-release-signed-${{ steps.var.outputs.tag }}.aab
        asset_content_type: application/zip