name: Android to playstore

defaults:
    run:
      working-directory: './mobileapp'
      
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Install bundle
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Configure Keystore
      run: |
        echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
        base64 -d -i keystore.jks.b64 > app/keystore.jks
        echo "storeFile=keystore.jks" >> keystore.properties
        echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
        echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
        echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties
      env:
        ANDROID_KEYSTORE_FILE: ${{ secrets.SIGNINGKEYBASE64 }}
        KEYSTORE_KEY_ALIAS: ${{ secrets.ALIAS }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYPASSWORD }}
        KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYPASSWORD }}

    - name: Create Google Play Config file
      id: write_file
      uses: timheuer/base64-to-file@v1.1
      with:
        fileName: 'play_config.json'
        encodedString: ${{ secrets.PLAY_CONFIG_JSON }}

    - name: Distribute app to Beta track 🚀
      run: bundle exec fastlane beta