name: Build and release android app

defaults:
    run:
      working-directory: './mobileapp'

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build-and-deploy:

    name: Build/Sign APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Tag
      id: var
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Build APK
      id: build
      run: bash ./gradlew assembleRelease

    - name: Sign APK
      uses: Tlaster/android-sign@v1
      with:
        releaseDirectory: |
          ./mobileapp/app/build/outputs/apk/release
          ./mobileapp/app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNEDKEYBASE64 }}
        output: ./mobileapp/app/build/release/signed
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
        keyPassword: ${{ secrets.KEYPASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "30.0.2"
