name: Build and release android app

defaults:
    run:
      working-directory: './mobileapp'

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build-and-deploy:

    name: Build/Sign APK
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Tag
      id: var
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Build APK
      id: build
      run: bash ./gradlew assembleRelease

    - name: Sign APK
      uses: Tlaster/android-sign@v1.2.2
      with:
        releaseDirectory: |
          ./mobileapp/app/build/outputs/apk/release
          ./mobileapp/app/build/outputs/bundle/release
        signingKeyBase64: ${{ MIIJ0wIBAzCCCYwGCSqGSIb3DQEHAaCCCX0Eggl5MIIJdTCCBYEGCSqGSIb3DQEHAaCCBXIEggVuMIIFajCCBWYGCyqGSIb3DQEMCgECoIIE+zCCBPcwKQYKKoZIhvcNAQwBAzAbBBSrxs0OHV/7K4tuOujJ1XiteL9iKQIDAMNQBIIEyE8hQW6kOj2sAx++eIihD0LnbC1pCEVa5cDJM2lAwzwXHtv65HqJ4bmkVulj62uJoNPvRn2vnE/b706X0zTI+2p+O/RI/D3T5zu5xTdsriqX/grZ9/sC9RjqNg6eTnaZ1dk4UYZhJjt/sw8MRUPpra6tbZ/PBTYr0Te0eXe2GZuULVGGYpGx8OeAWltIlFBEXvGPgourKsJlN1dbxAFuog9fTL32PH1+QhNXlXHLdfrrV2t3LDjCvSQ04SQmKI2s+NOfEYOsdgtDGJclfV1GgyITtwO8W6MwUyqQ1t4tiSrlRluxrOXJIBrcQwy06rZBm8nHiRlCFcy0notuujwDSaqTPn/gogDEj8EX/iKX2fyEamQXYDKIg5lghtfnCDudc7/qgfBgQ/AUdYVHUOY8v9CRNpu5RM+xbIoQAqbG9KqwvnCmpuAzB4Dp5XGZooIimmg0IXnjDJf08N3LCW6wmZ4Xp+VBM+lLMOGfmbWndAhfn3utJ13gLvqSHl4psjZjDX72dXDc58KsYes/TAU6GqRnEuPyv4Wzs25+8jYxMFNOAEbQ0E4as0iuh1b3J7gZ+Ex0r+mbct9mR/nf7OyNUwuJP6InX617/KGeSMkOuS2YVX5zZkyYNubxUUOnuknlBL7dwv3Mw8hIacscRo/Rjl2kAqJFR8WfQzsOdpUh6SLkE4/9tM7b1JO+ffnScLVcEBlWHiE+J/V170/NrFZHaoQRPHrz9jNGb6eXo5hDWwAPC0nzr9ENKVx/FmV6kbz+DuyeP0DyiXAN9KG+Wis90lK126h2ZULYlJBsuvBR3i6JX748Y7QwU7zVslxI551WKTE7LIbYevy5OY32EU5pFFQ8UuHZDy2FrTbbkuFS6SxBkXCpOQUKNddFrnYp0R1sbs8K32TL0GMyP/r/46OHAey3uv9D/o++XeJ5SCyYrJeyw4GtpBuyKlOeJDaGpBT3QSxooAAqeuGVTYiqI6HF0F6Rq9f6mIuu1ZcCvmpfewQEwqUbz757S7V0mkfxt/i90yTDXQzbFbfDO++cIutZSzImz54XhGVb2xT9/iZw75s9aCTO8yDlGMQASppuj2I5DoX029SY1dmS+giGg0BXQ5GUx+MmTBX4+E59naNhsrlti2BXk5Am3hsLse6y5zJ4aClxhIU5S+Y1Evj8Uh08dzxNDiIitgMYHrhinMb42Wx+cida44zvRcBzIPknqogkapfuR5YONZWwRAItY0PSv552dJM8eoMNQLe+lJ48nSyCuh3KG5puUJHJFjBgecm4e2UbJiTYaqtfWK/qimVpWCqbPiraex6vIvVMIfOPMs6UdXP/uv7IjEV50c1JWNR8G5KZB5oU3o5b3n8gYgK6Vx7af84WyAV4QGAM0S4WcWKI4DQWCcNGS2fyFoZUkD7b90WB+aDJDtwIW7G4CJqclIxdAoNwx2tbeLfMt/0N4/gkdefl/V75HZAPXxOqotTuUOIQJhvdCb70LKQ0N0FJB06g/XTYCGpRTOdLPY/2WdBmvUU8dsEe+THFFryEN1g5Nmnf6E1H4HbvOQlkHZFQEsY/8A3Zj6T5BaD8Oxc9Ad9FtxA90n/3mf7opbjF62GlqLE6/EK4VKW2+5ohHHPCto7wK0DcGKwzszFYMDMGCSqGSIb3DQEJFDEmHiQAaQBzAHYAaQByAHQAdQBhAGwAYQBzAHMAaQBzAHQAZQBuAHQwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTY1MDE1NjA1NjY1MzCCA+wGCSqGSIb3DQEHBqCCA90wggPZAgEAMIID0gYJKoZIhvcNAQcBMCkGCiqGSIb3DQEMAQYwGwQUWwqnj+GlfOJJUNGRnEgeWO65am8CAwDDUICCA5hOxV8bwFeh8jerW9eIqQ5jxIipyBRU2NsDJnZZWQZUQZmg60q96CXnlohraCnIUCGaL/mt6LJkVn5mMwn5IQqi51R4I2ra0qtGHrtQfWNaEh/CWuE+YvVRsqV9i4nP5JSanKP7EC8qf+sFdt+dl2oKoDtOrTorCdSsUD02nnBDST9ZLTcX/aCWUzBXTZx+H5A24v5VLLQgrOkXL5RF0/kBZ3X0ufTNNoxFU1XHsvbFEIbgh9U3lXrwRZQzYjgBcO+OwSKjl7yOCHc7dtG7xSumoV9P7e4u03TAo6hNOemy597w+b56lfxvi/kwpeLFjuHCcHwet3zbf54Ob9TY1NcJ5VoXT4bM/65+/p89Y/YzOIs9fi+nKV9FO5Puxg20FKf99CecTnVfdGiosyqfDotMbN6ySgTga15W7u66xNWPTomBGIdyKMDuGMt9bqH2MHICkVrQKwgIfVJPAD+54jKPmrJI1FKRjg/rJLn/LxpoG1TMQLvDcb6N7fwNACfg0d+ItqxuAUmD8PSrH0VahmwL64T9zVPJw9dOa0cHM+buvb39ftOvPQgx0DZ6gVQhZrtVhW4yOvuMlwnftdoFGRehl9zoXD3Jmnw4dsGl5Uo60ah1J2hYqY7E57O8Q9jIzatg5PR4FIqrxFfCcbY3iwSjgshJwJCTlMFUla/NR2r+p04XdUkRdHY5kGa1F9MG9lwKjXdiCH5NObPRoR4BUC8HD33zCOhDuiW19/l/shtNWPPNb60Eep4+bQfpdHdbxdoCPiIRRSTjfqWb3X5yhgNERdCoxkFuphVFvKEo6wDtlIiCgDpnR8ml0+EPh+vr4CVRQ3Jr3vtpNtQgW3YE0qSrIy+sw6H0X9+MAwuHxgMPXfN1kOfdsA6ExaXCSnGeF7Z2jjWQbSoyu60HcHD2mmY8yhBJh2L7cwP/6hvAbRI90cDbVrh3aP7f7ZvrOA9p03IO0Fp6j/cxojcf+v9kfcT42973NsTiBWMccl78t16r3csB97HkdvhRlxAA5/uD+c2oSJbdxMC/UGZqOjLqJ4BfSvC40C4RF9A36KwYLF9Fq/T2DNHPLXRGCz5ddMeRl6hMDP/8RIEgkIVPUgeApEKCbTnu8S3bKUZLroZjZlhebT3w5BB5b454+vaAqrBDQCMsUTeUiA4iNQvR0i66SyrKhdXFjqbEV0wG1fgvENYBJ82S1f/sp2O9mqPpJ0wIV6Gl74Uom1oMuzA+MCEwCQYFKw4DAhoFAAQUrRB16FrZTpZ5kWtubvXWHiq31wQEFON2pB6gr8juHpBczlOZ5No86Q9nAgMBhqA= }}
        output: ./mobileapp/app/build/release/signed
        alias: ${{ ISVirtualAssistent }}
        keyStorePassword: ${{ InfoSupportVirtualAssistant }}
        keyPassword: ${{ InfoSupportVirtualAssistant }}
      env:
        BUILD_TOOLS_VERSION: "30.0.2"
