name: Android Build

defaults:
  run:
    working-directory: './mobileapp'

on:
  push:
    branches:
    - android-release

jobs:
  build:
    name: Build/Sign APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Tag
        id: var
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}