name: Delete Preview Environment

on:
  push:
    branches:
      - feature/emergency

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Delete preview environment
        uses: okteto/destroy-preview@latest
        with:
          name: pr-51-0xboomie